version: "3.9"
services:
  mysql-con:
    container_name: mysql-con
    image: mysql
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Mig5@mig5
      MYSQL_DATABASE: card_repository
  payment-data-services:
    depends_on:
      - checkout-orchestrator
    build:
      context: ./payment-data-services
      dockerfile: Dockerfile
    working_dir: /payment-data-services
    image: nhiremathir/payment-data-services:v4
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
    ports:
      - 8080:8080
    env_file:
      - payment-data-services/db.env
#      - ./payment-data-services/db.env_file
  checkout-orchestrator:
    build:
      context: ./checkout-orchestrator
      dockerfile: Dockerfile
    working_dir: /checkout-orchestrator
    image: nhiremathir/checkout-orchestrator:v4
    volumes:
      - crypt:/checkout-orchestrator/crypt
    ports:
      - 8081:8081
    depends_on:
      - mysql-con

volumes:
  crypt: