version: "3.9"
services:
  mysql-con:
    container_name: mysql-con
    image: mysql
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Mig5@mig5
      MYSQL_DATABASE: card_repository
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
  payment-data-services:
    container_name: payment-data-services
    depends_on:
      checkout-orchestrator:
        condition: service_healthy
    build:
      context: ./payment-data-services
      dockerfile: Dockerfile
    working_dir: /payment-data-services
    image: nhiremathir/payment-data-services:v4
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
    ports:
      - 8080:8080
    env_file:
      - payment-data-services/db.env
#      - ./payment-data-services/db.env_file
  checkout-orchestrator:
    container_name: checkout-orchestrator
    build:
      context: ./checkout-orchestrator
      dockerfile: Dockerfile
    working_dir: /checkout-orchestrator
    image: nhiremathir/checkout-orchestrator:v4
    volumes:
      - crypt:/checkout-orchestrator/crypt
    ports:
      - 8081:8081
    depends_on:
      mysql-con:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/test"]

volumes:
  crypt: