apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  volumeMode: Filesystem
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /checkout-orchestrator-hostpath
    type: DirectoryOrCreate