apiVersion: v1
kind: Service
metadata:
  name: checkout-orchestrator-declarative-service
  labels:
    group: fsco
spec:
  selector:
    app: checkout-orchestrator
    tier: orchestration
  ports:
    - protocol: 'TCP'
      port: 8081
      targetPort: 8081
  type: LoadBalancer