apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-declarative-deployment
  labels:
    group: fsco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysql-container
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: mysqlpassword
            - name: MYSQL_DATABASE
              value: card_repository